name: cindy_radio
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.1.2
  audio_waveforms: ^1.0.4
  just_audio: ^0.9.33
  cached_network_image: ^3.2.3
  flutter_riverpod: ^2.3.6
  hooks_riverpod: ^2.3.6

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true


  assets:
    - asset/image/
    - asset/image/screenshot/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Nunito
      fonts:
         - asset: asset/font/Nunito-Black.ttf
         - asset: asset/font/Nunito-Bold.ttf
         - asset: asset/font/Nunito-ExtraBold.ttf
         - asset: asset/font/Nunito-ExtraLight.ttf
         - asset: asset/font/Nunito-Light.ttf
         - asset: asset/font/Nunito-Medium.ttf
         - asset: asset/font/Nunito-Regular.ttf
         - asset: asset/font/Nunito-semiBold.ttf
